config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :donations, only: [:create]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  namespace :users, path: ':user', as: :user do
    resources :causes
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/about", to: "static#about"
  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  resources :tweets, only: [:new, :create]
  root "static#home"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :donations
  has_many :causes
  validates :username, presence: true, length: { maximum: 25 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: valid_email_regex },
                    uniqueness: { case_sensitive: false }
  enum role: %w(default admin)
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def supported_causes
    self.donations.map do |donation|
      Cause.find(donation.cause_id)
    end
  end

  def self.from_omniauth(auth_info)
    where(id: auth_info[:uid]).first_or_create do |new_user|
      new_user.id = auth_info.uid
      new_user.username = auth_info.extra.raw_info.screen_name
      new_user.email = auth_info.info.email
      new_user.email = "#{new_user.username}@dreambuilder.com" if new_user.email.nil?
      new_user.password_digest = SecureRandom.base64
      new_user.oauth_token = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/users/causes_controller.rb
class Users::CausesController < ApplicationController
  before_action :valid_cause_owner?, only: [:edit, :destroy]
  before_action :valid_update?, only: [:update]

  def show
    redirect_to root_path unless show_cause?
    @cause = Cause.find(params[:id])
    @donation = Donation.new
  end

  def index
  end

  def new
    @cause = Cause.new
  end

  def create
    @cause = Cause.new(cause_params)
    if @cause.save
      @cause.other_admins << params[:cause][:other_admins]
      flash[:success] = "You dreamt about a #{@cause.title}"
      redirect_to user_cause_path(current_user.username, @cause)
    else
      flash.now[:error] = "Uh oh! You're not done dreaming. :`("
      render :new
    end
  end

  def edit
    @cause = Cause.find(params[:id])
  end

  def update
    @cause = Cause.find(params[:id])
    update_cause_attribues
    if URI(request.referrer).path == admin_dashboard_path
      redirect_to admin_dashboard_path
    else
      redirect_to user_cause_path(@cause.user.username, @cause)
    end
  end

  def destroy
    @cause = Cause.find(params[:id])
    backfill_donations(@cause)
    @cause.delete
    redirect_to user_path(User.find_by(username: params[:user]))
  end

  private

    def cause_params
      params.require(:cause).permit(:title,
                                    :description,
                                    :goal,
                                    :category_id,
                                    :user_id,
                                    :other_admins,
                                    :current_status,
                                    :image_url)
    end

    def valid_cause_owner?
      cause = Cause.find(params[:id])
      redirect_to root_path unless cause_owner? || (current_user.role == 'admin')
    end

    def valid_update?
      cause = Cause.find(params[:id])
      redirect_to root_path unless approved? || (current_user.role == 'admin')
    end

    def approved?
      params[:user].to_i == current_user_id || secondary_admin
    end

    def update_cause_attribues
      data = cause_params
      data[:user_id] = "#{@cause.user.id}"
      @cause.update_attributes(data)
      admins = @cause.other_admins.concat([params[:cause][:other_admins]])
      @cause.update_column(:other_admins, admins) if email_found?
    end

    def email_found?
      User.find_by(email: params[:cause][:other_admins])
    end

    def show_cause?
      Cause.find(params[:id]).current_status == 'active' || cause_owner?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_exists?, only: [:show]
  before_action :valid_user?, only: [:edit, :update]
  after_action :clear_attempted_donation, only: [:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Start dreaming, #{current_user.username} :-)"
      login_redirect(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = current_user
    holder = User.find_by(email: "gone@heaven.com")
    backfill_causes(user)
    user.delete
    session.clear
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation,
    :oauth_token, :oauth_token_secret)
  end

  def valid_user?
    user = User.find(params[:id])
    redirect_to root_path unless current_user_id == user.id
  end

  def user_exists?
    redirect_to root_path unless (User.all.pluck(:id).include?(params[:id].to_i))
  end
end

app/views/users/_causes_managed.html.erb
<%= link_to user_cause_path(causes_managed.user.username, causes_managed) do %>
  <li class="card cause-managed">
    <h6 class="center"><%= causes_managed.title %></h6>
    <div class="cause-img-container col s3">
      <%= image_tag(causes_managed.image_url, class: "valign") %>
    </div>
    <div class="col s9">
      <p class="col left-align">
        <%= causes_managed.description[0..185] %>...
      </p>
    </div>
    <div class="cause-funds center">
      <p>Raised: <span> <%= causes_managed.amount_raised %></span>
      <p>Goal: <span><%= causes_managed.goal %></span></p>
    </div>
    <% unless current_user.nil? ||  current_user.oauth_token.nil? %>
      <div class="tweet-managed-cause">
        <%= link_to image_tag('/assets/twitter-128.png', class: "twitter-logo"), new_tweet_path(cause_type: "managed", cause_id: causes_managed.id) %>
      </div>
    <% end %>
  </li>
<% end %>

app/views/users/_causes_supported.html.erb
  <li class="card cause-donated row">
    <%= link_to user_cause_path(causes_supported.user.username, causes_supported) do %>
      <div class="col s2">
        <span>$<%= causes_supported.amount_raised %> </span>
      </div>
      <h6 class="truncate col s6">
        <%= causes_supported.title %>
      </h6>
    <% end %>
    <% unless current_user.nil? || current_user.oauth_token.nil? %>
      <div class="col s1 push-s3">
        <%= link_to image_tag('/assets/twitter-128.png', class: "twitter-logo"), new_tweet_path(cause_type: "supported", cause_id: causes_supported.id) %>
      </div>
    <% end %>
  </li>

app/views/users/edit.html.erb
<div class="container">
  <h4>Edit Account Info</h4>
  <%= form_for(@user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :username %>
    <%= f.text_field :username  %>
    <br>

    <%= f.label :email %>
    <%= f.text_field :email  %>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Update Account", class: "wave-effect waves-light btn light-green darken-4" %>
  <% end  %>
  <% if current_user_id == @user.id %>
    <%= link_to "Delete Account", user_path(@user), method: :delete, class: "btn red right" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h4>Create a New Account</h4>
  <br>
  <%= form_for(@user) do |f| %>

    <%= render "shared/error_messages", object: f.object %>

    <div class="input-field">
      <%= f.label :username %>
      <%= f.text_field :username  %>
    </div>

    <div class="input-field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="input-field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="input-field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div>
      <%= f.submit "Create Account", class: "wave-effect waves-light btn darkslategray" %>
    </div>
  <% end  %>
  <div>
    <p>
      Already a dreamer? Click below to login:
    </p>
    <%= link_to("Login", login_path, class: "waves-effect waves-light btn darkslategray") %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container user-header center">
  <h3><%= @user.username.capitalize %>'s Dream Board</h3>
  <% if current_user_id == @user.id %>
    <span><%= link_to "Edit Account Info", edit_user_path(@user), class: "btn" %></span>
    <span><%= link_to "Build a Dream", new_user_cause_path(@user), class: "btn" %></span>
  <% end %>
</div>

<div class="row">
  <div class="col s6">
    <div id="causes-managed" class="causes-container">
    <h4 class="center">Causes Managed</h4>
      <ul>
        <%= render partial: "users/causes_managed", collection: @user.causes %>
      </ul>
    </div>
  </div> <!-- end of managed causes -->
  <div class="col s6">
    <div class="causes-container">
    <h4 class="center">Causes Supported</h4>
      <ul id="causes-supported">
        <%= render partial: "users/causes_supported", collection: @user.supported_causes %>
      </ul>
  </div>
</div> <!-- end of row -->