config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :donations, only: [:create]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  namespace :users, path: ':user', as: :user do
    resources :causes
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/about", to: "static#about"
  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  resources :tweets, only: [:new, :create]
  root "static#home"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :causes
  validates :title, uniqueness: true, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::BaseController
    before_action :set_categories, only: [:edit, :index, :create]
    before_action :set_category, only: [:edit, :update, :destroy]

    def index
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:success] = "New category #{@category.title} created"
        redirect_to admin_categories_path
      else
        flash[:error] = "Something went wrong, dreamer."
        render "index"
      end
    end

    def edit
    end

    def update
      if @category.update(category_params)
        flash[:success] = "#{@category.title} updated"
        redirect_to admin_categories_path
      else
        render "edit"
      end
    end

    def destroy
      @category.destroy
      flash[:success] = "#{@category.title} removed"
      redirect_to admin_categories_path
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    # random cause for featured cause on bottom of page
    @cause = Cause.all.first
    # creates an array of category cause counts to be used in javascript
    @amounts = Category.all.map{|category| category.causes.count}
    gon.amount = @amounts
  end

  def show
    @category = Category.find(params[:id])
    # pagination
    @causes = (Cause.active_causes_for_category(params)).paginate(:page => params[:page]).order('id ASC')
  end
end

app/views/admin/categories/_form.html.erb
<div class="container center">
  <%= form_for [:admin, @category] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.text_field :title %>
    <%= f.label :title %>
    <br>
    <br>
    <%= f.submit "Stache that Category!", class: "btn light-green darken-4" %>
  <% end %>
</div>

app/views/admin/categories/_index_alone.html.erb
<div class="container">
  <div class="center">
    <h4>You are the Stache Category Master</h4>
  </div>
<table>
  <thead>
    <tr>
      <th data-field="title">Title</th>
      <th data-field="quantity">Number o' Staches</th>
      <th data-field="actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <div id="category-<%= category.id %>">
      <tr>
        <td><%= link_to category.title, category, class: "btn light-green darken-4" %></td>
        <td><%= category.staches.count %></td>

        <td>
          <%= link_to "Edit", edit_admin_category_path(category) %>
          <% if category.staches.empty? %>
          /
            <%= link_to "Remove", admin_category_path(category), method: :delete %>
          <% end %>
        </td>
      </tr>
    </div>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/categories/_new.html.erb
<div class="center">
  <h4>Create New Category</h4>
  <div class="container">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<%= render "index_alone" %>
<div class="center">
  <h4>Editing <%= @category.title %></h4>
  <div class="container">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<%= render "index_alone" %>
<%= render "new" %>