config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :donations, only: [:create]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  namespace :users, path: ':user', as: :user do
    resources :causes
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/about", to: "static#about"
  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  resources :tweets, only: [:new, :create]
  root "static#home"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :causes
  validates :title, uniqueness: true, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::BaseController
    before_action :set_categories, only: [:edit, :index, :create]
    before_action :set_category, only: [:edit, :update, :destroy]

    def index
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:success] = "New category #{@category.title} created"
        redirect_to admin_categories_path
      else
        flash[:error] = "Something went wrong, dreamer."
        render "index"
      end
    end

    def edit
    end

    def update
      if @category.update(category_params)
        flash[:success] = "#{@category.title} updated"
        redirect_to admin_categories_path
      else
        render "edit"
      end
    end

    def destroy
      @category.destroy
      flash[:success] = "#{@category.title} removed"
      redirect_to admin_categories_path
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    # random cause for featured cause on bottom of page
    @cause = Cause.all.first
    # creates an array of category cause counts to be used in javascript
    @amounts = Category.all.map{|category| category.causes.count}
    gon.amount = @amounts
  end

  def show
    @category = Category.find(params[:id])
    # pagination
    @causes = (Cause.active_causes_for_category(params)).paginate(:page => params[:page]).order('id ASC')
  end
end

app/views/categories/_category.html.erb
<div class="fades<%= category.id % 3 %>">
  <%= link_to category_path(category) do %>
      <div class="col s4">
        <div class="card-panel indigo lighten-5 center cat<%= category.id %>">
          <span class="colored"><%= category.title %>
          </span>
        </div>
      </div>
  <% end %>
</div>

app/views/categories/_cause.html.erb
<div class="col s4">
  <div class="card medium">
    <h6 class="truncate center"><%= cause.title %></h6>
    <div class="card-image">
      <img src= <%= cause.image_url %>>
    </div>
    <div class="card-content">
      <p class="truncate"><%= cause.description %></p>
    </div>
    <div class="card-action">
      <%= link_to "View this cause", user_cause_path(cause.user.username, cause) %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<%= Gon::Base.render_data %>
<div class="container">
  <h4 class="center">Dreams By Category:</h4>
  <div class="row">
    <%= render @categories %>
  </div>
</div>

<div class="container center">
  <h3>Featured Dream</h3>
  <%= image_tag("#{@cause.image_url}", id:"cause-img-container left") %>
  <div class="center">
    <h3><%= @cause.title %></h3>
    <h6 class="center-text"><%= @cause.description %></h6>
    <h6 class="light grey-text text-lighten-3">
      <%= link_to "Donate", user_cause_path(@cause.user.username, @cause), class: "btn" %>
    </h6>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h4 class="center"> <%= @category.title %> </h4><br>
  <div class="row">
    <div class="center">
      <%= will_paginate @causes %>
    </div>
    <%= render partial: "categories/cause", collection: @causes %>
  </div>
</div>