config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :donations, only: [:create]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  namespace :users, path: ':user', as: :user do
    resources :causes
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/about", to: "static#about"
  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  resources :tweets, only: [:new, :create]
  root "static#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamBuilder</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat|Kameron|Unica+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo"><%= image_tag("logo2white.png", :alt => "unicorn", class: "logo-img") %></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to "Categories", categories_path, class: "hoverable" %> </li>
        <% if current_user %>
          <li> <%= link_to "Build Your Dream", new_user_cause_path(current_user.username), class: "hoverable" %> </li>
          <li> <%= link_to "User Dashboard", user_path(current_user), class: "hoverable" %></li>
          <li> <%= link_to "Log Out (#{current_user.username})", logout_path, method: :delete, class: "hoverable" %> </li>
          <% else %>
          <li> <%= link_to "Build Your Dream", new_user_path, class: "hoverable" %> </li>
          <li> <%= link_to "Login", login_path, class: "hoverable" %> </li>
          <li> <%= link_to "Sign Up", new_user_path, class: "hoverable" %> </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <%= image_tag("unicorn.png", :alt => "unicorn", class: "unicorn") %>
<% flash.each do |type, msg| %>
  <%= content_tag :div, sanitize(msg), class: "flash_#{type} flash" %>
<% end %>

<%= yield %>
<br><br><br><br><br>
<footer class="footer-bar">
  <div class="footer-content">
    <p class="colored footer-content hide-on-small-only">
       ...to the moon!!!!!!
    </p>
    <a href="/"><h5 class="white-text footer-content">Dream Builder</h5></a>
  </div>
  <a class="white-text footer-link" href="/about">About</a>
  <% if current_user && current_user.admin? %>
    <%= link_to "Admin Dashboard", admin_dashboard_path, class: "red-text footer-link" %></li>
  <% end %>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
<!-- <script type="text/javascript">
$(document).ready(function(){
  $('#fades').delay( 2000 ).fadeTo('slow', 0);
  $('.slider').slider({full_width: true});
});
</script> -->

</body>
</html>